# Generated by Django 3.2.4 on 2021-06-07 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='期限'),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(1, '未完了'), (2, '作業中'), (3, '完了')], default=1),
        ),
    ]
